package ca.sariarra.poker.logic;

public enum HandAction {

	BETTING_ROUND_LIMIT,
	BETTING_ROUND_LIMIT_BIG,
	BETTING_ROUND_NO_LIMIT,
	BETTING_ROUND_POT_LIMIT,
	SHOWDOWN,
	POST_BLIND_BETS,
	DEAL_2_HOLE,
	DEAL_4_HOLE,
	DEAL_2_HOLE_1_EXPOSED,
	DEAL_1_EXPOSED,
	DEAL_1_HOLE,
	DEAL_3_COMMUNITY,
	DEAL_1_COMMUNITY,
	DRAW_UPTO_5,
	DRAW_UPTO_4;
}
